const editAddress = require("../edit-address-pageobject/edit-address")

describe('Address Book', () => {
    function randomEmail(){
        const randomString = Math.random().toString(36).substring(2,9)
        const email = randomString + "@mailinator.com"
        return email
    }
    let email = randomEmail()

    function randomTelephone(){
        const randomString = Math.random().toString(36).substring(2,9)
        const telephone = randomString
        return telephone
    }
    let telephone = randomTelephone()

    function randomPostalCode(){
        const randomString = Math.random().toString(36).substring(2,9)
        const postalCode = randomString 
        return postalCode
    }
    let postalCode = randomPostalCode()

    beforeEach(() => {
        cy.visit('')
    })
    it.only('Register Account', () => {
        editAddress.registerAccount()
        cy.MagentoRegisterForms('Ariq Ali', 'Saman', email, 'TeSt123098', 'TeSt123098')
        editAddress.clickRegister()
        editAddress.verifyRegister()
    })
    it('Navigate To Edit Address Page', () => {
        editAddress.signInAccount()
        cy.MagentoLoginForms( email, 'TeSt123098')
        editAddress.clickSignIn()
        editAddress.clickMyAccount()
        editAddress.clickAddressBook()
        editAddress.verifyEditAddress()
    })
    it('Edit Address - Negative (Empty Forms)', () => {
        editAddress.signInAccount()
        cy.MagentoLoginForms( email, 'TeSt123098')
        editAddress.clickSignIn()
        editAddress.clickMyAccount()
        editAddress.clickAddressBook()
        editAddress.verifyEditAddress()
        cy.MagentoEditEmptyForms()
        editAddress.clickSaveAddress()
        editAddress.verifyFirstName()
        editAddress.verifyLastName()
        editAddress.verifyTelephone()
        editAddress.verifyStreet()
        editAddress.verifyCity()
        editAddress.verifyRegion()
        editAddress.verifyPostal()
        editAddress.verifyCountry()
       
    })
    it('Edit Address - Positive (Complete Forms)', () => {
        editAddress.signInAccount()
        cy.MagentoLoginForms( email, 'TeSt123098')
        editAddress.clickSignIn()
        editAddress.clickMyAccount()
        editAddress.clickAddressBook()
        editAddress.verifyEditAddress()
        cy.MagentoEditCompleteForms(' 2', ' 3', 'PT Kerja Keras', telephone, 'Jln. Raya 1', 'Jln. Raya 2', 'Jln. Raya 3', 'Jakarta', 'Texas', postalCode, 'Indonesia')
        editAddress.validationFirstName()
        editAddress.validationLastName()
        editAddress.validationTelephone()
        editAddress.validationCity()
        editAddress.validationPostal()
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
    })
    it.only('Edit Address - Change Billing and Shipping Address', () => {
        editAddress.signInAccount()
        cy.MagentoLoginForms( email, 'TeSt123098')
        editAddress.clickSignIn()
        editAddress.clickMyAccount()
        editAddress.clickAddressBook()
        editAddress.verifyEditAddress()
        cy.MagentoEditCompleteForms(' 2', ' 3', 'PT Kerja Keras', telephone, 'Jln. Raya 1', 'Jln. Raya 2', 'Jln. Raya 3', 'Jakarta', 'Texas', postalCode, 'Indonesia')
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
        editAddress.clickChangeAddress()
        editAddress.verifyEditAddress2()
        cy.MagentoEditAddress('Jakarta Pusat', postalCode)
        editAddress.verifyBillingAddress()
        editAddress.verifyShippingAddress()
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
    })
    it.only('Edit Address - Add New Address', () => {
        editAddress.signInAccount()
        cy.MagentoLoginForms( email, 'TeSt123098')
        editAddress.clickSignIn()
        editAddress.clickMyAccount()
        editAddress.clickAddressBook()
        editAddress.verifyEditAddress()
        cy.MagentoEditCompleteForms(' 2', ' 3', 'PT Kerja Keras', telephone, 'Jln. Raya 1', 'Jln. Raya 2', 'Jln. Raya 3', 'Jakarta', 'Texas', postalCode, 'Indonesia')
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
        editAddress.clickAddNewAddress()
        editAddress.verifyEditAddress()
        cy.MagentoAddNewAddress('PT Sakti', telephone, 'Jln. Raya 5', 'Jln. Raya 7', 'Jln. Raya 9', 'Bandung', 'Arizona', postalCode, 'Indonesia')
        editAddress.clickBillingCheckbox()
        editAddress.clickShippingCheckbox()
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
    })
    it.only('Edit Address - Edit Address Option', () => {
        editAddress.signInAccount()
        cy.MagentoLoginForms( email, 'TeSt123098')
        editAddress.clickSignIn()
        editAddress.clickMyAccount()
        editAddress.clickAddressBook()
        editAddress.verifyEditAddress()
        cy.MagentoEditCompleteForms(' 2', ' 3', 'PT Kerja Keras', telephone, 'Jln. Raya 1', 'Jln. Raya 2', 'Jln. Raya 3', 'Jakarta', 'Texas', postalCode, 'Indonesia')
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
        editAddress.clickAddNewAddress()
        editAddress.verifyEditAddress()
        cy.MagentoAddNewAddress('PT Sakti', telephone, 'Jln. Raya 5', 'Jln. Raya 7', 'Jln. Raya 9', 'Bandung', 'Arizona', postalCode, 'Indonesia')
        editAddress.clickBillingCheckbox()
        editAddress.clickShippingCheckbox()
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
        editAddress.clickEditAddress()
        cy.MagentoEditAddress('Tangerang Selatan', postalCode)
        editAddress.clickBillingCheckbox()
        editAddress.clickShippingCheckbox()
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
    })
    it.only('Edit Address - Delete Address Option', () => {
        editAddress.signInAccount()
        cy.MagentoLoginForms( email, 'TeSt123098')
        editAddress.clickSignIn()
        editAddress.clickMyAccount()
        editAddress.clickAddressBook()
        editAddress.verifyEditAddress()
        cy.MagentoEditCompleteForms(' 2', ' 3', 'PT Kerja Keras', telephone, 'Jln. Raya 1', 'Jln. Raya 2', 'Jln. Raya 3', 'Jakarta', 'Texas', postalCode, 'Indonesia')
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
        editAddress.clickAddNewAddress()
        editAddress.verifyEditAddress()
        cy.MagentoAddNewAddress('PT Sakti', telephone, 'Jln. Raya 5', 'Jln. Raya 7', 'Jln. Raya 9', 'Bandung', 'Arizona', postalCode, 'Indonesia')
        editAddress.clickBillingCheckbox()
        editAddress.clickShippingCheckbox()
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
        editAddress.clickEditAddress()
        cy.MagentoEditAddress('Tangerang Selatan', postalCode)
        editAddress.clickBillingCheckbox()
        editAddress.clickShippingCheckbox()
        editAddress.clickSaveAddress()
        editAddress.verifySaveAddress()
        editAddress.clickDeleteAddress()
        editAddress.clickCancelDeleteAddress()
        editAddress.clickDeleteAddress()
        editAddress.clickYesDeleteAddress()
        editAddress.clickSignOut()
    })
})
